/* TRANSFERINDO DADOS DAS TABELAS IMPORTADAS PARA AS NOVAS */

SELECT TOP 10 * FROM Tb_CG_OLIST_CUSTOMER;

CREATE TABLE Tb_ACT_OLIST_CUSTOMER(
	CUSTOMER_ID NVARCHAR(150),
	CUSTOMER_UNIQUE_ID NVARCHAR(150),
	CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
	CUSTOMER_CITY NVARCHAR(100),
	CUSTOMER_STATE CHAR(2)
);

INSERT INTO Tb_ACT_OLIST_CUSTOMER
SELECT * FROM Tb_CG_OLIST_CUSTOMER;

SELECT TOP 10 * FROM Tb_CG_OLIST_GEOLOCATION;

CREATE TABLE Tb_ACT_OLIST_GEOLOCATION(
	GEOLOCATION_ZIP_CODE_PREFIX NVARCHAR(15),
	GEOLOCATION_LAT NVARCHAR(100),
	GEOLOCATION_LNG NVARCHAR(100),
	GEOLOCATION_CITY NVARCHAR(100),
	GEOLOCATION_STATE CHAR(2)
);

INSERT INTO Tb_ACT_OLIST_GEOLOCATION
SELECT * FROM Tb_CG_OLIST_GEOLOCATION;

SELECT TOP 10 * FROM Tb_CG_OLIST_ORDER_ITEMS;

CREATE TABLE Tb_ACT_OLIST_ORDER_ITEMS(
	ORDER_ID NVARCHAR(150),
	ORDER_ITEM_ID NVARCHAR(100),
	PRODUCT_ID NVARCHAR(150),
	SELLER_ID NVARCHAR(150),
	SHIPPING_LIMIT_DATE DATETIME,
	PRICE MONEY,
	FREIGHT_VALUE MONEY
);

INSERT INTO Tb_ACT_OLIST_ORDER_ITEMS
SELECT * FROM Tb_CG_OLIST_ORDER_ITEMS;

SELECT TOP 10 * FROM Tb_CG_OLIST_ORDER_PAYMENTS;

CREATE TABLE Tb_ACT_OLIST_ORDER_PAYMENTS(
	ORDER_ID NVARCHAR(150),
	PAYMENT_SEQUENTIAL NVARCHAR(15),
	PAYMENT_TYPE NVARCHAR(50),
	PAYMENT_INSTALLMENTS NVARCHAR(15),
	PAYMENT_VALUE MONEY
);

INSERT INTO Tb_ACT_OLIST_ORDER_PAYMENTS
SELECT * FROM Tb_CG_OLIST_ORDER_PAYMENTS;

SELECT TOP 10 * FROM Tb_CG_OLIST_ORDERS;

CREATE TABLE Tb_ACT_OLIST_ORDERS(
	ORDER_ID NVARCHAR(150),
	CUSTOMER_ID NVARCHAR(150),
	ORDER_STATUS NVARCHAR(50),
	ORDER_PURCHASE_TIMESTAMP DATETIME,
	ORDER_APPROVED_AT DATETIME,
	ORDER_DELIVERED_CARRIER_DATE DATETIME,
	ORDER_DELIVERED_CUSTOMER_DATE DATETIME,
	ORDER_ESTIMATED_DELIVERY_DATE DATETIME
);

INSERT INTO Tb_ACT_OLIST_ORDERS
SELECT * FROM Tb_CG_OLIST_ORDERS;

SELECT TOP 10 * FROM Tb_CG_OLIST_PRODUCTS;

CREATE TABLE Tb_ACT_OLIST_PRODUCTS(
	PRODUCT_ID NVARCHAR(150),
	PRODUCT_CATEGORY_NAME NVARCHAR(150),
	PRODUCT_NAME_LENGHT NVARCHAR(15),
	PRODUCT_DESCRIPTION_LENGHT NVARCHAR(15),
	PRODUCT_PHOTOS_QTY NVARCHAR(15),
	PRODUCT_WEIGHT_G NVARCHAR(15),
	PRODUCT_LENGHT_CM NVARCHAR(15),
	PRODUCT_HEIGHT_CM NVARCHAR(15),
	PRODUCT_WIDTH_CM NVARCHAR(15)
);

INSERT INTO Tb_ACT_OLIST_PRODUCTS
SELECT * FROM Tb_CG_OLIST_PRODUCTS;

SELECT TOP 10 * FROM Tb_CG_OLIST_SELLERS;

CREATE TABLE Tb_ACT_OLIST_SELLERS(
	SELLER_ID NVARCHAR(150),
	SELLER_ZIP_CODE_PREFIX NVARCHAR(15),
	SELLER_CITY NVARCHAR(100),
	SELLER_STATE CHAR(2)
);

INSERT INTO Tb_ACT_OLIST_SELLERS
SELECT * FROM Tb_CG_OLIST_SELLERS;

SELECT TOP 10 * FROM Tb_CG_PRODUCT_CATEGORY;

CREATE TABLE Tb_ACT_PRODUCT_CATEGORY(
	PRODUCT_CATEGORY_NAME NVARCHAR(100),
	PRODUCT_CATEGORY_NAME_ENGLISH NVARCHAR(100)
);

INSERT INTO Tb_ACT_PRODUCT_CATEGORY
SELECT * FROM Tb_CG_PRODUCT_CATEGORY;

DROP TABLE Tb_CG_OLIST_CUSTOMER, Tb_CG_OLIST_GEOLOCATION, Tb_CG_OLIST_ORDER_ITEMS, Tb_CG_OLIST_ORDER_PAYMENTS,
Tb_CG_OLIST_ORDERS, Tb_CG_OLIST_PRODUCTS, Tb_CG_OLIST_SELLERS, Tb_CG_PRODUCT_CATEGORY;